exclude: '^$|migrations|settings|scripts|tests'
fail_fast: false
repos:

- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.7.1
  hooks:
    - id: add-trailing-comma

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: git@github.com:pre-commit/mirrors-yapf.git
  rev: v0.25.0
  hooks:
    - id: yapf
      additional_dependencies: ['futures']
      args: ['--style=.style.yapf', '--parallel', '--in-place']

# When calling `pre-commit autoupdate`, this repo needs to be commented because it fails
- repo: git@github.com:FalconSocial/pre-commit-python-sorter.git
  rev: b57843b0b874df1d16eb0bef00b868792cb245c2  # higher than 1.0.4 (latest release)
  hooks:
    - id: python-import-sorter
      args: ['--silent-overwrite']
      exclude: 'wsgi.py'

- repo: git@github.com:myint/docformatter.git
  # Latest release v1.0 does not contains the .pre-commit-hooks.yaml file
  rev: 7cb0c50b674680e28cae8c4c1add6b43ed2ccb91
  hooks:
    - id: docformatter
      args: ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']

- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    # Disabled because yapf is better for our purpose
    # - id: autopep8-wrapper
    - id: check-added-large-files
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
      exclude: 'static'
    - id: fix-encoding-pragma
    - id: check-merge-conflict
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: flake8
      additional_dependencies: [
      'flake8-blind-except',
      'flake8-coding',
      'flake8-commas',
      'flake8-comprehensions',
      'flake8-deprecated',
      'flake8-docstrings',
      'flake8-meiqia',
      'flake8-mutable',
      'flake8-pep3101',
      'flake8-quotes',
      'flake8-string-format',
      'flake8-tidy-imports',
      # These are good but are broken with current pydocstyle version
      # 'flake8-print',
      # 'flake8-debugger',
      # 'flake8-todo',
      ]

- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
    - id: prospector
      # https://github.com/pre-commit/pre-commit/issues/178
      language: system
      files: '\.py$'
      args: ['--profile=prospector', '--profile-path=.']

      # We need run ``pip install -r requirements/testing.txt -r
      # requirements/lint.txt`` in the virtualenv where our RTD
      # project is installed because we are using ``language: system``
      # for this hook
      # additional_dependencies: []
